language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Kukushkina_lab
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./ArrListTest/ArrListTest
  - ./StackTest/StackTest
  - ./QueueTest/QueueTest
notifications:
  email: false
